version: '3'

services:
    web:
        image: sodiumafrica/sodiumserver:1.0
        volumes:
            - ./docker/growthpad.local.conf:/etc/nginx/servers/growthpad.conf:rw
            - ./:/var/www/:rw
        ports:
            - 17000:80
        restart: 'always'

    adminer:
        image: clue/adminer
        ports:
            - 17001:80
        restart: 'always'

    db:
        image: mariadb
        volumes:
            - ./docker/mysql/:/var/lib/mysql/:rw
        environment:
            MYSQL_DATABASE: growthpad.irenkenya.com
            MYSQL_ROOT_PASSWORD: jS35n9YmZppjxRDfhfY5MJvc5tKztp
        restart: 'always'