version: '3'

services:
    web:
        image: sodiumafrica/sodiumserver:1.0
        volumes:
            - ./docker/vhost.conf:/etc/nginx/servers/growthpad.conf:rw
            - ./:/var/www/:rw
        ports:
            - 15031:80
        restart: 'always'
        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 15333:80
        volumes:
            - /sessions
