version: '3'

services:
    web:
        image: sodiumafrica/sodiumserver:1.0
        volumes:
            - ./docker/growthpad.local.conf:/etc/nginx/servers/growthpad.conf:rw
            - ./:/var/www/:rw
        ports:
            - 17000:80
        restart: 'always'