<?php

return [
    'counties' => [
        'BARINGO'         => 'Baringo County',
        'BOMET'           => 'Bomet County',
        'BUNGOMA'         => 'Bungoma County',
        'BUSIA'           => 'Busia County',
        'ELGEYO-MARAKWET' => 'Elgeyo-Marakwet County',
        'EMBU'            => 'Embu County',
        'GARISSA'         => 'Garissa County',
        'HOMA-BAY'        => 'Homa-bay County',
        'ISIOLO'          => 'Isiolo County',
        'KAJIADO'         => 'Kajiado County',
        'KAKAMEGA'        => 'Kakamega County',
        'KERICHO'         => 'Kericho County',
        'KIAMBU'          => 'Kiambu County',
        'KILIFI'          => 'Kilifi County',
        'KIRINYAGA'       => 'Kirinyaga County',
        'KISII'           => 'Kisii County',
        'KISUMU'          => 'Kisumu County',
        'KITUI'           => 'Kitui County',
        'KWALE'           => 'Kwale County',
        'LAIKIPIA'        => 'Laikipia County',
        'LAMU'            => 'Lamu County',
        'MACHAKOS'        => 'Machakos County',
        'MAKUENI'         => 'Makueni County',
        'MANDERA'         => 'Mandera County',
        'MARSABIT'        => 'Marsabit County',
        'MERU'            => 'Meru County',
        'MIGORI'          => 'Migori County',
        'MOMBASA'         => 'Mombasa County',
        'MURANGA'         => 'Muranga County',
        'NAIROBI'         => 'Nairobi County',
        'NAKURU'          => 'Nakuru County',
        'NANDI'           => 'Nandi County',
        'NAROK'           => 'Narok County',
        'NYAMIRA'         => 'Nyamira County',
        'NYANDARUA'       => 'Nyandarua County',
        'NYERI'           => 'Nyeri County',
        'SAMBURU'         => 'Samburu County',
        'SIAYA'           => 'Siaya County',
        'TAITA-TAVETA'    => 'Taita-Taveta County',
        'TANA RIVER'      => 'Tana River County',
        'THARAKA-NITHI'   => 'Tharaka-Nithi County',
        'TRANS-NZOIA'     => 'Trans-Nzoia County',
        'TURKANA'         => 'Turkana County',
        'UASIN GISHU'     => 'Uasin Gishu County',
        'VIHIGA'          => 'Vihiga County',
        'WAJIR'           => 'Wajir County',
        'WEST POKOT'      => 'West Pokot County',
    ],

    'market_types' => [
        'LOCAL'    => 'Local Market',
        'NATIONAL' => 'National Market',
        'REGIONAL' => 'Regional Market',
    ],
    
    'countries' => [
        'KE' => 'Kenya',
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua And Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia And Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island & Mcdonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle Of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KI' => 'Kiribati',
        'KR' => 'Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthelemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome And Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia And Sandwich Isl.',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'SX' => 'Sint Maarten',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad And Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks And Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis And Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
        'CW' => 'Curaçao',
        'KP' => 'North Korea',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'SS' => 'South Sudan',
    ],


    'services' => [
        'farm' => [
            'BDP'  => 'Business Development and Planning',
            'ARK'  => 'Accounts and Record Keeping',
            'EFPS' => 'Extension services/ Farm Planning',
        ],

        'leasing' => [
            'FARM'      => 'Farm equipment',
            'LOGISTICS' => 'Logistics',
            'VENDOR'    => 'Vendor Services',
        ],

        'market' => [
            'BPLAN'     => 'Business Plan',
            'MARKETING' => 'Marketing',
            'BRANDING'  => 'Branding',
            'PACKAGING' => 'Packaging',
        ],

        'consulting' => [
            'LEGAL' => 'Legal Services',
            'BR'    => 'Business Registration',
            'ACC'   => 'Accounting Services',
        ],

        'toolset' => [
            'farm-tools' => [
                'Plows'             => 'Plows',
                'Planter'           => 'Planter',
                'Harrow'            => 'Harrow',
                'Sprinkler'         => 'Sprinkler',
                'Hand cultivator'   => 'Hand cultivator',
                'Hanging scale'     => 'Hanging scale',
                'Pruning sheers'    => 'Pruning sheers',
                'Animal Traps'      => 'Animal Traps',
                'Hammer'            => 'Hammer',
                'Sickle'            => 'Sickle',
                'Mower'             => 'Mower',
                'Bee keeper smoker' => 'Bee keeper smoker',
                'Beehives'          => 'Beehives',
                'Chicken coop'      => 'Chicken coop',
            ],

            'logistics' => [
                'Trucks'       => 'Trucks',
                'Lorries'      => 'Lorries',
                'Pick up'      => 'Pick up',
                'Motor Cycle'  => 'Motor Cycle',
                'Wheel barrow' => 'Wheel barrow',
            ],

            'vendor' => [
                'Fruit Presser'           => 'Fruit Presser',
                'Grain Mill'              => 'Grain Mill',
                'Juice extractors'        => 'Juice extractors',
                'Steamer'                 => 'Steamer',
                'Cream Separator'         => 'Cream Separator',
                'Milk Pasteurizer'        => 'Milk Pasteurizer',
                'Chicken – Egg incubator' => 'Chicken – Egg incubator',
                'Honey centrifuges'       => 'Honey centrifuges',
                'Cheese press'            => 'Cheese press',
                'Butter churn'            => 'Butter churn',
                'Groundnut decorticator'  => 'Groundnut decorticator',

            ],
        ],
    ],

    'team' => [
        [
            'name'  => 'Nelson Ameyo',
            'email' => 'nelson@blackpay.co.ke',
        ],
        [
            'name'  => 'James Shikwati',
            'email' => 'james@irenkenya.com',
        ],
        [
            'name'  => 'Leonard Mwasi',
            'email' => 'leonard@irenkenya.com',
        ],
        [
            'name'  => 'Winnie Nanjala',
            'email' => 'nanjala@irenkenya.com',
        ],
        [
            'name'  => 'Simon Achieno',
            'email' => 'simon@irenkenya.com',
        ],
    ],

    'google_api_key' => 'AIzaSyDZ659_y2QdDyFRf49FbKnAHzPCzALlb3M',

    'formTypes' => [
        'CONSULTING' => 'Formalization and Consulting',
        'FARM-MANAGEMENT' => 'Farm Management',
        'LEASING' => 'Leasing Solutions',
        'MARKET-ADVISORY' => 'Market Growth Advisory'
    ],
];